///////////////////////////////////////////////////////////////////////////////
    Copyright (c) 2013, 2022, Oracle and/or its affiliates.

    Licensed under the Universal Permissive License v 1.0 as shown at
    https://oss.oracle.com/licenses/upl.
///////////////////////////////////////////////////////////////////////////////

= Spring Boot

== Spring Boot

The Spring Boot module of the Coherence Spring project builds upon the core Spring module and enhances it by providing
dedicated auto-configuration support for Spring Boot as well support for Spring Boot configuration properties,
and support for Spring Boot's new ConfigData API to use Coherence as a source of configuration data.

Getting your first Coherence powered Spring Boot application off the ground could not be easier. Create a basic Spring
Boot app using https://start.spring.io/[start.spring.io].

Add the Coherence Spring Boot Starter to your generated app's `pom.xml`:

.Maven
[source,xml,indent=0,subs="verbatim,quotes,attributes"]
----
<dependencies>
    <dependency>
        <groupId>com.oracle.coherence.spring</groupId>
        <artifactId>coherence-spring-boot-starter</artifactId>
        <version>{version-coherence-spring}</version>
    </dependency>
    <dependency>
        <groupId>com.oracle.coherence.ce</groupId>
        <artifactId>coherence</artifactId>
        <version>{version-coherence}</version>
    </dependency>
</dependencies>
----

NOTE: Instead of Coherence CE you can also specify the commercial version of Coherence. The minimum supported commercial
version is Oracle Coherence `14.1.1.2206` Feature Pack.

This will be enough to start up a default instance of Coherence with default settings. E.g., inject Coherence beans into
your Spring Controllers, Services and other components:

[source,java]
----
@CoherenceCache("myCacheName")
private NamedCache<Long, String> namedCache;
----

In order to dive deeper, please see the link:refdocs/reference/html/quickstart.html[Quickstart Guide], the
https://github.com/coherence-community/todo-list-example/tree/main/java/spring-server[To-do List Sample], and also
refer to the link:refdocs/reference/html/index.html[reference guide].
