[[coherence-spring-documentation]]
= Coherence Spring Documentation
include::attributes.adoc[]

Welcome to the reference documentation of Coherence Spring, a collection of several
libraries that will help you to integration Coherence with the wider Spring ecosystem.

This section provides a brief overview of the Coherence Spring reference documentation.

[[about]]
== About the Documentation
The Coherence Spring reference guide is available as:

* {coherence-spring-docs}/html[Multi-page HTML]
* {coherence-spring-docs}/htmlsingle[Single page HTML]
* {coherence-spring-docs}/pdf/coherence-spring-reference.pdf[PDF]

The latest copy is available at {coherence-spring-current-docs}.

[[getting-help]]
== Getting Help
If you have trouble with Spring Coherence, we would like to help.

* Try the <<howto.adoc#howto, How-to documents>>.
  They provide solutions to the most common questions.
* Learn the Coherence basics.
  All Spring Coherence module directly support Oracle Coherence.
  Check the https://coherence.community[Coherence CE] web-site for general Coherence
  targeted reference documentation.
* Learn the Spring basics.
  Spring Coherence builds on several other Spring projects.
  Check the https://spring.io[spring.io] web-site for general reference documentation.
  If you are starting out with Spring, try one of the https://spring.io/guides[guides].
* Ask a question.
  Chat with us directly on https://join.slack.com/t/oraclecoherence/shared_invite/zt-9ufv220y-Leudk0o5ntgNV0xraa8DNw[Slack].
  We also monitor https://stackoverflow.com[stackoverflow.com] for questions tagged with
  https://stackoverflow.com/tags/coherence[`coherence`].
* Report bugs with Spring Coherence via {github-issues}[GitHub Issues].

NOTE: All of Coherence Spring is open source, including the documentation.
If you find problems with the docs or if you want to improve them, please {coherence-spring-code}[get involved].



[[news]]
== What is new?
Instructions for how to upgrade from earlier versions of Spring Boot are provided on the project {github-wiki}[wiki].
Follow the links in the in the {github-wiki}#release-notes[release notes] section to find the version that you want to upgrade to.

Upgrading instructions are always the first item in the release notes.
If you are more than one release behind, please make sure that you also review the release notes of the versions that you jumped.

You should always ensure that you are running a {github-wiki}/Supported-Versions[supported version] of Spring Boot.


[[boot-documentation-first-steps]]
== First Steps
If you are getting started with Spring Boot or 'Spring' in general, start with <<getting-started.adoc#getting-started, the following topics>>:

* *From scratch:* <<getting-started.adoc#getting-started-introducing-spring-boot, Overview>> | <<getting-started.adoc#getting-started-system-requirements, Requirements>> | <<getting-started.adoc#getting-started-installing-spring-boot, Installation>>
* *Tutorial:* <<getting-started.adoc#getting-started-first-application, Part 1>> | <<getting-started.adoc#getting-started-first-application-code, Part 2>>
* *Running your example:* <<getting-started.adoc#getting-started-first-application-run, Part 1>> | <<getting-started.adoc#getting-started-first-application-executable-jar, Part 2>>


== Working with Coherence Spring

Ready to actually start using Spring Boot? <<using-spring-boot.adoc#using-boot, We have you covered>>:

* *Build systems:* <<using-spring-boot.adoc#using-boot-maven, Maven>> | <<using-spring-boot.adoc#using-boot-gradle, Gradle>> | <<using-spring-boot.adoc#using-boot-ant, Ant>> | <<using-spring-boot.adoc#using-boot-starter, Starters>>
* *Best practices:* <<using-spring-boot.adoc#using-boot-structuring-your-code, Code Structure>> | <<using-spring-boot.adoc#using-boot-configuration-classes, @Configuration>> | <<using-spring-boot.adoc#using-boot-auto-configuration, @EnableAutoConfiguration>> | <<using-spring-boot.adoc#using-boot-spring-beans-and-dependency-injection, Beans and Dependency Injection>>
* *Running your code:* <<using-spring-boot.adoc#using-boot-running-from-an-ide, IDE>> | <<using-spring-boot.adoc#using-boot-running-as-a-packaged-application, Packaged>> | <<using-spring-boot.adoc#using-boot-running-with-the-maven-plugin, Maven>> | <<using-spring-boot.adoc#using-boot-running-with-the-gradle-plugin, Gradle>>
* *Packaging your app:* <<using-spring-boot.adoc#using-boot-packaging-for-production, Production jars>>
* *Spring Boot CLI:* <<spring-boot-cli.adoc#cli, Using the CLI>>


== Learning about Spring Boot Features
Need more details about Spring Boot's core features?
<<spring-boot-features.adoc#boot-features, The following content is for you>>:

* *Core Features:* <<spring-boot-features.adoc#boot-features-spring-application, SpringApplication>> | <<spring-boot-features.adoc#boot-features-external-config, External Configuration>> | <<spring-boot-features.adoc#boot-features-profiles, Profiles>> | <<spring-boot-features.adoc#boot-features-logging, Logging>>
* *Web Applications:* <<spring-boot-features.adoc#boot-features-spring-mvc, MVC>> | <<spring-boot-features.adoc#boot-features-embedded-container, Embedded Containers>>
* *Working with data:* <<spring-boot-features.adoc#boot-features-sql, SQL>> | <<spring-boot-features.adoc#boot-features-nosql, NO-SQL>>
* *Messaging:* <<spring-boot-features.adoc#boot-features-messaging, Overview>> | <<spring-boot-features.adoc#boot-features-jms, JMS>>
* *Testing:* <<spring-boot-features.adoc#boot-features-testing, Overview>> | <<spring-boot-features.adoc#boot-features-testing-spring-boot-applications, Boot Applications>> | <<spring-boot-features.adoc#boot-features-test-utilities, Utils>>
* *Extending:* <<spring-boot-features.adoc#boot-features-developing-auto-configuration, Auto-configuration>> | <<spring-boot-features.adoc#boot-features-condition-annotations, @Conditions>>
