[[coherence-spring-documentation]]
= Coherence Spring Documentation
include::attributes.adoc[]

Welcome to the reference documentation of {coherence-spring-code}[Coherence Spring], a collection of several
libraries that will help you to integrate {oracle-coherence}[Coherence] with the wider {spring}[Spring] ecosystem.

This section provides a brief overview of the Coherence Spring reference documentation.

[[about]]
== About the Documentation
The Coherence Spring reference guide is available as:

* {coherence-spring-docs}/html[Multi-page HTML]
* {coherence-spring-docs}/htmlsingle[Single page HTML]
* {coherence-spring-docs}/pdf/coherence-spring-reference.pdf[PDF]

[[getting-help]]
== Getting Help
If you have trouble with Spring Coherence, we would like to help.

* Try the <<howto.adoc#howto, How-to documents>>.
  They provide solutions to the most common questions.
* Learn the Coherence basics.
  All Spring Coherence module directly support Oracle Coherence.
  Check the https://coherence.community[Coherence CE] web-site for general Coherence
  targeted reference documentation.
* Learn the Spring basics.
  Spring Coherence builds on several other Spring projects.
  Check the https://spring.io[spring.io] web-site for general reference documentation.
  If you are starting out with Spring, try one of the https://spring.io/guides[guides].
* Ask a question.
  Chat with us directly on https://join.slack.com/t/oraclecoherence/shared_invite/zt-9ufv220y-Leudk0o5ntgNV0xraa8DNw[Slack].
  We also monitor https://stackoverflow.com[stackoverflow.com] for questions tagged with
  https://stackoverflow.com/tags/oracle-coherence[oracle-coherence].
* Report bugs with Spring Coherence via {github-issues}[GitHub Issues].

NOTE: All of Coherence Spring is open source, including the documentation.
If you find problems with the docs or if you want to improve them, please {coherence-spring-code}[get involved].

[[news]]
== What is new?

In order to see what changes were made from earlier versions of Coherence Spring,
see the {coherence-spring-website}//history.html[Change History] as well as the
{github-releases}[GitHub Releases] page.

[[first-steps]]
== First Steps
If you are getting started with Spring Boot or 'Spring' in general, start with <<getting-started.adoc#getting-started, the following topics>>:

* *From scratch:* <<getting-started.adoc#getting-started-introducing-spring-boot, Overview>> | <<getting-started.adoc#getting-started-system-requirements, Requirements>> | <<getting-started.adoc#getting-started-installing-spring-boot, Installation>>
* *Tutorial:* <<getting-started.adoc#getting-started-first-application, Part 1>> | <<getting-started.adoc#getting-started-first-application-code, Part 2>>
* *Running your example:* <<getting-started.adoc#getting-started-first-application-run, Part 1>> | <<getting-started.adoc#getting-started-first-application-executable-jar, Part 2>>

