[[coherence-spring-documentation]]
= Coherence Spring Documentation
include::attributes.adoc[]

Welcome to the reference documentation of {coherence-spring-code}[Coherence Spring], a collection of libraries that will
help you to integrate {oracle-coherence}[Oracle Coherence] with the wider {spring}[Spring] ecosystem.

{oracle-coherence}[Oracle Coherence] is a scalable, fault-tolerant, cloud-ready, distributed platform for building
grid-based applications and reliably storing data. The product is used at scale, for both compute and raw storage, in a
vast array of industries such as critical financial trading systems, high performance telecommunication products and
e-commerce applications.

Coherence Spring features dedicated support to bootstrap Oracle Coherence and to inject Coherence resources into Spring
beans as well as to inject Spring beans into Coherence resources. Spring's dependency injection (DI) support simplifies
application code as Oracle Coherence _maps_, _caches_ and _topics_ are just injected instead of being obtained explicitly
via Coherence APIs. Furthermore, using annotated _event listener_ methods simplifies building reactive code that responds
to Coherence cache events.

Before diving into the technical aspects of the reference documentation let's provide a brief overview of the Coherence
Spring reference documentation, where to start, how to obtain further helper and more.

[[about]]
== About the Documentation
The Coherence Spring reference guide is available as:

* {coherence-spring-docs}/html[Multi-page HTML]
* {coherence-spring-docs}/htmlsingle[Single page HTML]
* {coherence-spring-docs}/pdf/coherence-spring-reference.pdf[PDF]

[[getting-help]]
== Getting Help
If you run into issues with Spring Coherence, we are here to help.

* _Try the <<quickstart.adoc#quickstart, Quickstart>>._
  The Quickstart will give you an overview of Coherence Spring's
  capabilities and provides a sample application to get you started.
* _Learn the Coherence basics._ Please have at least some basic understanding of Oracle Coherence since all Spring Coherence
  modules depend on it. Check out the https://coherence.community[Coherence CE] web-site for general Coherence
  targeted reference documentation.
* _Learn the Spring basics._
  The reference guide assumes that you have a basic understanding of {spring-framework}[Spring Framework] and
  {spring-boot-website}[Spring Boot]. Coherence Spring utilizes several other Spring projects. Check the
  {spring-io-website}[spring.io] web-site for general reference documentation. If you are starting out with Spring, try
  one of the https://spring.io/guides[guides] or generate a starter project using https://start.spring.io/.
* _Ask a question._
  Chat with us directly on https://join.slack.com/t/oraclecoherence/shared_invite/zt-9ufv220y-Leudk0o5ntgNV0xraa8DNw[Slack].
  We also monitor https://stackoverflow.com[stackoverflow.com] for questions tagged with
  https://stackoverflow.com/tags/oracle-coherence[oracle-coherence].
* _Contribute._
  Report bugs with Spring Coherence via {github-issues}[GitHub Issues]. Both, Coherence CE and Coherence Spring are Open
  Source Software (OSS) under the liberal <<legal.adoc#legal, Universal Permissive License (UPL)>>. Contributing back is
  a great way to attain a deeper understanding of our projects.

NOTE: All of _Coherence Spring_ is open source, including the documentation.
If you find problems with the docs or if you want to improve them, please {coherence-spring-code}[get involved].

[[news]]
== What is new?

In order to see what changes were made from earlier versions of Coherence Spring, see the
{coherence-spring-website}index.html#/dev/06_history[Change History] as well as the {github-releases}[GitHub Releases] page.

[[first-steps]]
== First Steps
If you are getting started with Coherence Spring, start with the <<quickstart.adoc#quickstart, Quickstart>>. It is a great
way to see a working solution quickly. Particularly if you are relatively new to Spring, continue with the
<<spring-boot.adoc#spring-boot>> chapter next.

NOTE: Another great example application is the Spring Boot implementation of the
https://github.com/coherence-community/todo-list-example/tree/master/java[To-do List application].

The reference documentation makes a distinction between
{spring-framework}[Spring Framework] and {spring-boot-website}[Spring Boot]. At its very core, Spring Framework provides
Dependency Injection (DI) or Inversion Of Control (IOC) to Java applications. Furthermore, Spring Framework gives developers
comprehensive infrastructure support for developing Java applications.

Spring Boot on the other hand, is an opinionated extension to the Spring Framework by:

- Eliminating boilerplate configurations
- Providing Auto-Configuration for other Spring modules and third-party integrations
- Metrics + health checks

The vast majority of new Spring projects will utilize Spring Boot. Nonetheless, please also study the Spring Framework targeted
chapters as Spring Frameworks is the foundation for everything related to Spring Boot.
