[[spring-boot]]
= Coherence Spring Boot
include::attributes.adoc[]

This section dives into the Coherence Spring Boot module. It explains how to use
Coherence's dedicated support for {spring-docs-boot}[Spring Boot], e.g. Autoconfiguration.

[[spring-boot-getting-started]]
== Getting Started

In order to start using Coherence with Spring Boot you have to add the `coherence-spring-boot-starter` dependency as well
as the desired version of Coherence.

.Adding the Coherence Spring Boot Starter Dependency
====
.Maven
[source,xml,indent=0,subs="verbatim,quotes,attributes",role="primary"]
----
<dependencies>
    <dependency>
        <groupId>com.oracle.coherence.spring</groupId>
        <artifactId>coherence-spring-boot-starter</artifactId>
        <version>{coherence-spring-version}</version>
    </dependency>
    <dependency>
        <groupId>com.oracle.coherence.ce</groupId>
        <artifactId>coherence</artifactId>
        <version>{coherence-version}</version>
    </dependency>
</dependencies>
----

.Gradle
[source,groovy,indent=0,subs="verbatim,quotes,attributes",role="secondary"]
----
dependencies {
    compile("com.oracle.coherence.spring:coherence-spring-boot-starter:{coherence-spring-version}")
    compile("com.oracle.coherence.ce:coherence:{coherence-version}")
}
----
====

IMPORTANT: As Coherence Spring takes advantage of the new Coherence Bootstrap API, it requires Oracle Coherence CE version
`20.12` or higher.

[[spring-boot-using-coherence]]
== Using Coherence with Spring Boot

By adding the `coherence-spring-boot-starter` dependency, AutoConfiguration will be activated via the `CoherenceAutoConfiguration`
class. This will also bind the `CoherenceProperties` for further configuration. The configuration for Spring Boot's
Coherence support may look like the following:

[source,yaml]
----
coherence:
  logging:
    destination: slf4j
    logger-name: MyCoherence
  sessions:
  - name: default
    config: "coherence-cache-config.xml"
    priority: 1
  - name: test
    config: "test-coherence-config.xml"
    priority: 2
  properties:
    coherence.log.limit: 400
    coherence.log.level: 1
----

The following configuration properties are available.

.Coherence Configuration Properties
|===
|Key |Default Value |Description

| coherence.logging.destination
|
| The type of the logging destination. Default to `slf4j` if not set.

| coherence.logging.severity-level
|
| Specifies which logged messages are emitted to the log destination. The legal values are `-1` to `9`.
No messages are emitted if `-1` is specified. More log messages are emitted as the log level is increased.

| coherence.logging.logger-name
|
|

| coherence.logging.message-format
|
|

| coherence.logging.character-limit
|
|

| coherence.properties.*
|
| Any native Coherence properties

| coherence.sessions[0].name
|
|

| coherence.sessions[0].type
|
| Represents the various session type that can be configured: CLIENT, SERVER, GRPC

| coherence.sessions[0].config
|
| The Coherence cache configuration URI for the session

| coherence.sessions[0].priority
|
| The priority order to be used when starting the session. Sessions will be started with the lowest priority first.

| coherence.sessions[0].scope-name
|
| The scope name for the session.

|===

IMPORTANT: All but the session property are translated into native Coherence properties. If both
Spring Boot property AND a native property `coherence.properties.*` are configured, the Spring Boot
property is used.

For a list of available native properties, please consult the reference guide chapter on
https://docs.oracle.com/en/middleware/standalone/coherence/14.1.1.0/develop-applications/system-property-overrides.html#GUID-32230D28-4976-4147-A887-0A0120FF5C7E[System Property Overrides].

[[spring-boot-customize-coherence]]
== Customize Coherence

[[spring-boot-config-data-api]]
== Coherence Support of the Spring Boot ConfigData API

Starting with Spring Boot `2.4.x` you can define your own
https://spring.io/blog/2020/08/14/config-file-processing-in-spring-boot-2-4[custom config locations]. This allows you to
import these as property sources. As such, Coherence Spring allows you to use a Coherence cluster as a source of
configuration data for your Spring Boot based applications.

NOTE: Please also consult the Spring Boot reference guide on https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-external-config[Externalized Configuration],
especially the chapter on https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-external-config-files-importing[Importing Additional Data].

NOTE: Please also see the chapter on xref:spring-cloud-config.adoc#spring-cloud-config[Coherence Spring Cloud Config].

[[spring-boot-caching]]
== Using Coherence as Spring Caching Provider

As long as `coherence-spring-boot-starter` is added to your project, and caching is enabled via `@EnableCaching`,
Coherence Autoconfiguration will automatically provide a `CacheManager` to the ApplicationContext. However, the
`CacheManager` is only added if no `CacheManager` was configured explicitly beforehand.

Once that is in place, you can take advantage of
https://docs.spring.io/spring-boot/docs/current/reference/html/spring-boot-features.html#boot-features-caching[Spring's Cache abstraction]
backed by Coherence and use Spring's annotations such as `@Cacheable`, `@CacheEvict`, `@CachePut` etc.

[NOTE]
====
When learning about Coherence's Spring cache abstraction support, please familiarize yourself with the
following resources:

- <<spring-cache.adoc#quickstart,Coherence Core Spring Cache Support>>
- {spring-docs-boot}spring-boot-features.html#boot-features-caching[Spring Boot's reference documentation's support regarding caching]
- https://docs.spring.io/spring-boot/docs/current/reference/html/spring-boot-features.html#boot-features-caching[The Cache Abstraction]
chapter in the core Spring Framework reference guide
====


