:snapshot-version: 3.0.0-SNAPSHOT
:website: https://spring.coherence.community/
:milestone: 3.0.0-M2

= Welcome to the Oracle Coherence Spring Project

image:https://github.com/coherence-community/coherence-spring/workflows/CI%20Coherence%20Spring/badge.svg[CI Coherence Spring,link=https://github.com/coherence-community/coherence-spring/actions]
image:https://img.shields.io/badge/Coherence-Join%20Slack-brightgreen[Chat with us on slack,link=https://join.slack.com/t/oraclecoherence/shared_invite/zt-9ufv220y-Leudk0o5ntgNV0xraa8DNw]
image:https://img.shields.io/stackexchange/stackoverflow/t/oracle-coherence?label=%20StackOverflow%20%7C%20oracle-coherence[Stack Exchange questions,link=https://stackoverflow.com/questions/tagged/oracle-coherence]
image:https://img.shields.io/twitter/follow/OracleCoherence?style=social[Twitter Follow,link=https://twitter.com/OracleCoherence]

The Coherence Spring project provides bootstrapping support of https://coherence.community/[Oracle Coherence] for
https://spring.io/projects/spring-framework[Spring Framework] and https://spring.io/projects/spring-boot[Spring Boot].
Coherence Spring also provides a set of components to aid in the integration of Oracle Coherence and various other projects of the Spring eco-system:

- Spring Data
- Spring's Cache Abstraction
- Spring Boot Config API + Spring Cloud Config Server (In-process)
- Spring Session

== Documentation

Detailed project documentation is available on the Coherence Spring website. This includes the reference documentation in various formats (Multi-page/Single-page HTML, PDF), as well as extensive JavaDoc for the Coherence Spring source code.

[width="75%"]
|=======
|*{milestone}* | {website}{milestone}[Website] |{website}{milestone}/refdocs/reference/html/index.html[Multi-page HTML] |{website}{milestone}/refdocs/reference/htmlsingle/index.html[Single-page HTML] | {website}{milestone}/refdocs/reference/pdf/coherence-spring-reference.pdf[PDF] | {website}{milestone}/refdocs/api/index.html[API Doc.]
|*{snapshot-version}* | {website}{snapshot-version}[Website] |{website}{snapshot-version}/refdocs/reference/html/index.html[Multi-page HTML] |{website}{snapshot-version}/refdocs/reference/htmlsingle/index.html[Single-page HTML] | {website}{snapshot-version}/refdocs/reference/pdf/coherence-spring-reference.pdf[PDF] | {website}{snapshot-version}/refdocs/api/index.html[API Doc.]
|=======

NOTE: The http://maven.apache.org[Apache Maven]-based snapshots and releases for this project are published to
http://repo1.maven.org/maven2/com/oracle/coherence/spring/[Maven Central].

== Quick Start

In order to get started quickly, please read the reference guide as it provides a detailed
https://spring.coherence.community/{snapshot-version}/refdocs/reference/htmlsingle/index.html#quickstart[Quickstart chapter].

Through the reference documentation we will also refer to various demo and sample applications. Those are part of this
repository, and you can find those in the
https://github.com/coherence-community/coherence-spring/tree/master/samples[samples] module.

== Building from Source

=== Requirements

In order to build Coherence Spring, you need to have installed:

- https://www.oracle.com/java/technologies/javase-jdk11-downloads.html[JDK 11]
- https://help.github.com/set-up-git-redirect[Git]

NOTE: When using Coherence Spring merely as a dependency in a project, without intending to build the project from
source code, then an installed _JDK 8_ version is sufficient.

=== Check out sources

Check out the project using https://git-scm.com/[Git]:

[source,bash,indent=0]
----
git clone https://github.com/coherence-community/coherence-spring.git
cd coherence-spring
----

Coherence Spring uses https://maven.apache.org/[Apache Maven] as build tool. You do not need to have Maven installed to
build the project. Simply use the provided https://github.com/takari/maven-wrapper[Maven Wrapper], e.g.:

- *Windows:* `mvnw.cmd clean package`
- *Linux/Mac:* `./mvnw clean package`

=== Build the entire project

Build the entire project using https://maven.apache.org/[Maven]:

[source,bash]
----
./mvnw clean package -Pspring
----

==== Offline Builds

In case you are offline and you run into issues building the project, e.g.
the Coherence cluster as part of JUnit tests does not start up successfully, then
you may have to provide additional command line arguments:

[source,bash]
----
./mvnw clean package -Pspring -DargLine="-Dcoherence.localhost=127.0.0.1 -Djava.net.preferIPv4Stack=true"
----

=== Build the Documentation

[source,bash]
----
./mvnw clean package -pl coherence-spring-docs -Pspring
----

=== Build the project website

[source,bash]
----
./mvnw clean install -pl coherence-spring-site -Pspring
----

=== Deploy the project website

[source,bash]
----
./mvnw com.github.github:site-maven-plugin:site -pl coherence-spring-site -Pspring
----

== Getting Support

In case you have questions or if you run into issue using the Coherence Spring project, please feel free to reach out to
us either via:

- https://stackoverflow.com/tags/oracle-coherence[Stackoverflow] using the _oracle-coherence_ tag
- https://join.slack.com/t/oraclecoherence/shared_invite/zt-9ufv220y-Leudk0o5ntgNV0xraa8DNw[Slack]

Both support channels are monitored by the project community.

== Contributing

We would love to review your https://help.github.com/articles/creating-a-pull-request[Pull requests]. Please see the
link:CONTRIBUTING.md[contributor guidelines] for details.

== License

Coherence Spring is Open Source software released under link:LICENSE.txt[The Universal Permissive License] (UPL), Version 1.0.

