///////////////////////////////////////////////////////////////////////////////
    Copyright (c) 2000, 2021, Oracle and/or its affiliates.

    Licensed under the Universal Permissive License v 1.0 as shown at
    http://oss.oracle.com/licenses/upl.
///////////////////////////////////////////////////////////////////////////////

= Source Code
:description: Oracle Coherence Spring Website
:keywords: coherence, spring, java, documentation

// DO NOT remove this header - it might look like a duplicate of the header above, but
// both they serve a purpose, and the docs will look wrong if it is removed.

== Source Code

The Source Code for the Oracle Coherence Spring Integration is hosted by https://github.com[github.com].

It is located here:
https://github.com/coherence-community/coherence-spring

Alternatively if you're not using or want to avoid setting up http://git-scm.com[git]
can download a zip containing of the latest development branch from here:

https://github.com/coherence-community/coherence-spring/archive/master.zip

The branching model adopted for development and releases is as outlined by Vincent Driessen in
http://nvie.com/posts/a-successful-git-branching-model[A successful Git branching model]

[IMPORTANT]
====
. Source Code and Documentation is licensed under link:license.html[CDDL-1.0].
. *Read-Only Access* is provided to the public.
. *Pull Requests* are welcome as long as you become a official link:contributions.html[contributor])
====