# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: CI Coherence Spring
on:
  workflow_dispatch:
  schedule:
    - cron: "0 5 * * *"
  push:
    branches: [ master ]
  pull_request:
    types:
      - opened
      - synchronized
      - committed
    branches:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Set up JDK 11
        uses: actions/setup-java@v2.0.0
        with:
          distribution: 'adopt'
          java-version: '11'
      - name: Build and test with Maven
        run: |
          git config --global user.email "github-action@users.noreply.github.com"
          git config --global user.name "GitHub Action"
          ./mvnw clean verify -B -Pspring -Powasp --settings .mvn/settings.xml
        env:
          MAVEN_GITHUB_TOKEN: "${{secrets.GITHUB_TOKEN}}"
          MAVEN_SONATYPE_USERNAME: "${{secrets.MAVEN_SONATYPE_USERNAME}}"
          MAVEN_SONATYPE_TOKEN: "${{secrets.MAVEN_SONATYPE_TOKEN}}"

