# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: CI Coherence Spring
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: '1.8'
        server-id: github
        server-password: MAVEN_GITHUB
        server-username: ""
    - name: Build with Maven
      run: mvn clean package -Pspring
    - name: Update Website
      run: mvn -pl coherence-spring-site deploy
      env:
        MAVEN_GITHUB: ${{ secrets.MAVEN_GITHUB }}
