# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: CI Coherence Spring
on:
  workflow_dispatch:
  schedule:
    - cron: "0 5 * * *"
  push:
    branches: [ master ]
  pull_request:
    types:
      - opened
      - synchronized
      - committed
    branches:
      - '*'
jobs:
  build:
    if: github.repository_owner == 'coherence-community'
    strategy:
      matrix:
        java-version: [ 11 ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v2.5.0
        with:
          distribution: 'adopt'
          java-version: ${{ matrix.java-version }}
      - name: Cache SonarCloud packages
        if: "matrix.java-version == 11"
        uses: actions/cache@v1
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2-
      - name: Build and test with Maven + Sonar
        if: "github.event_name != 'pull_request' && matrix.java-version == 11"
        run: |
          git config --global user.email "github-action@users.noreply.github.com"
          git config --global user.name "GitHub Action"
          ./mvnw clean verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=coherence-community_coherence-spring -B -Pspring -Powasp -Pcoverage --settings .mvn/settings.xml
        env:
          MAVEN_GITHUB_TOKEN: "${{secrets.GITHUB_TOKEN}}"
          GITHUB_TOKEN: "${{secrets.GITHUB_TOKEN}}"
          SONAR_TOKEN: "${{secrets.SONAR_TOKEN}}"
          MAVEN_SONATYPE_USERNAME: "${{secrets.MAVEN_SONATYPE_USERNAME}}"
          MAVEN_SONATYPE_TOKEN: "${{secrets.MAVEN_SONATYPE_TOKEN}}"
      - name: Build and test with Maven - ${{ matrix.java-version }}
        if: "github.event_name == 'pull_request' || (github.event_name != 'pull_request' && matrix.java-version != 11)"
        run: |
          git config --global user.email "github-action@users.noreply.github.com"
          git config --global user.name "GitHub Action"
          ./mvnw clean verify -B -Pspring -Powasp,jdk${{ matrix.java-version }} --settings .mvn/settings.xml
        env:
          MAVEN_GITHUB_TOKEN: "${{secrets.GITHUB_TOKEN}}"
          MAVEN_SONATYPE_USERNAME: "${{secrets.MAVEN_SONATYPE_USERNAME}}"
          MAVEN_SONATYPE_TOKEN: "${{secrets.MAVEN_SONATYPE_TOKEN}}"
      - name: Clean Maven cache
        run: |
          find ~/.m2/repository -type d -name '*SNAPSHOT' | xargs rm -fr
