name: Schedule Nightly Builds

on:
  workflow_dispatch:
  schedule:
    - cron: "0 5 * * *"
jobs:
  schedule:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        branch: [main, 3.3.x]
    steps:
      - uses: benc-uk/workflow-dispatch@v1.2.3
        with:
          workflow: CI Coherence Spring
          ref: ${{ matrix.branch }}
